// <auto-generated />
namespace Xogum.AcessoBanco.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class TableMot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableMot));
        
        string IMigrationMetadata.Id
        {
            get { return "201910202019152_TableMot"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
