// <auto-generated />
namespace Xogum.AcessoBanco.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class EnderecoContratoAtualizacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EnderecoContratoAtualizacao));
        
        string IMigrationMetadata.Id
        {
            get { return "201911202242475_EnderecoContratoAtualizacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
